export const DEFAULT_OPERATIONS = [
  { code: 'D02', name: 'Prescription', price: 25, category: 'Diagnostic' },
  { code: 'DS003', name: 'Oral Examination / Consultation', price: 150, category: 'Diagnostic' },
  { code: 'DS005', name: 'X-ray Periapical', price: 100, category: 'Diagnostic' },
  { code: 'DS011', name: 'Diagnostic Cast (Standard)', price: 500, category: 'Diagnostic' },
  { code: 'DS012', name: 'Diagnostic Cast (Orthodontic)', price: 770, category: 'Diagnostic' },
  { code: 'DS013', name: 'OPG Xray', price: 200, category: 'Diagnostic' },

  { code: '021', name: 'Luxe Dental Clinic', price: 20, category: 'Restorative' },
  { code: 'D070', name: 'Tooth Gem Placement (Large-size) -1', price: 200, category: 'Restorative' },
  { code: 'D070a', name: 'Tooth Gem Placement- (Large-size)-3pcs', price: 500, category: 'Restorative' },
  { code: 'D071', name: 'Tooth Gem Placement (small-size)-3pcs', price: 250, category: 'Restorative' },
  { code: 'D071a', name: 'Tooth Gem Placement (Small-size)-1pcs', price: 100, category: 'Restorative' },
  { code: 'PR007', name: 'Whitening - per 30min session (In-Office)', price: 600, category: 'Restorative' },
  { code: 'PR007a', name: 'Whitening -(Home Kit Tray)', price: 700, category: 'Restorative' },
  { code: 'R014', name: 'Filling - Composite Class I', price: 700, category: 'Restorative' },
  { code: 'R015', name: 'Filling - Composite Class II - MO', price: 700, category: 'Restorative' },
  { code: 'R016', name: 'Filling - Composite Class II - DO', price: 700, category: 'Restorative' },
  { code: 'R017', name: 'Filling - Composite Class II - MOD', price: 700, category: 'Restorative' },
  { code: 'R018', name: 'Filling - Composite Class III - M', price: 700, category: 'Restorative' },
  { code: 'R019', name: 'Filling - Composite Class III - D', price: 700, category: 'Restorative' },
  { code: 'R020', name: 'Filling - Composite Class IV', price: 770, category: 'Restorative' },
  { code: 'R021', name: 'Filling - Composite Class V - Per quadrant', price: 700, category: 'Restorative' },
  { code: 'R021a', name: 'Filling - Composite Class V - CTLS- Every extra tooth', price: 150, category: 'Restorative' },
  { code: 'R023', name: 'Medicated Filling', price: 900, category: 'Restorative' },
  { code: 'R025', name: 'Filling - Composite mod P', price: 825, category: 'Restorative' },
  { code: 'R027', name: 'Inlay - Ceramic Restoration E-max', price: 2750, category: 'Restorative' },
  { code: 'R028', name: 'Inlay- Zirconium Restoration (Premolar)', price: 3080, category: 'Restorative' },
  { code: 'R029', name: 'Inlay - Zirconia Restoration (Multi-Layer)', price: 3850, category: 'Restorative' },
  { code: 'R030', name: 'Inlay - Cast Metal Restoration (Precious Alloy)', price: 2750, category: 'Restorative' },
  { code: 'R031', name: 'Filling - Onlay Composite', price: 1100, category: 'Restorative' },
  { code: 'R033', name: 'E-max onlay/inlay Restoration', price: 2750, category: 'Restorative' },
  { code: 'R037', name: 'Onlay Cast Metal Restoration (Precious Alloy)', price: 2750, category: 'Restorative' },
  { code: 'R038', name: 'Fiber Post Placement (Per Tooth)', price: 600, category: 'Restorative' },
  { code: 'R039', name: 'Core-Build Up Restoration', price: 900, category: 'Restorative' },
  { code: 'R040', name: 'Filling - GIC Simple', price: 600, category: 'Restorative' },
  { code: 'R041', name: 'Internal Bleaching', price: 500, category: 'Restorative' },
  { code: 'R042', name: 'Enameloplasty', price: 1000, category: 'Restorative' },

  { code: 'I001', name: 'Dental Implant Placement Surgery', price: 22000, category: 'Implant' },

  { code: 'O001', name: 'Fixed Orthodontic Appliance – Metal Braces', price: 5000, category: 'Orthodontics' },
  { code: 'O001_1', name: 'Invisalign-Clear Aligners (Express)', price: 17000, category: 'Orthodontics' },
  { code: 'O002', name: 'Invisalign-Clear Aligners (Lite Plan)', price: 30000, category: 'Orthodontics' },
  { code: 'O004', name: 'Invisalign-Clear Aligners (Moderate Plan)', price: 35000, category: 'Orthodontics' },
  { code: 'O004a', name: 'Invisalign-Clear Aligners (Comprehensive Plan - 3yr)', price: 45000, category: 'Orthodontics' },
  { code: 'O004b', name: 'Invisalign-Clear Aligners (Comprehensive Plan - 5yr)', price: 49000, category: 'Orthodontics' },
  { code: 'O005', name: 'Orthodontic Initial Assessment/Consultation', price: 1500, category: 'Orthodontics' },
  { code: 'O005a', name: 'Orthodontic Follow-up Review/Consultation', price: 700, category: 'Orthodontics' },
  { code: 'O007', name: 'Removable Orthodontic Appliance', price: 5000, category: 'Orthodontics' },
  { code: 'O008', name: 'Orthodontic Retainer (Post-Treatment)', price: 5000, category: 'Orthodontics' },

  { code: 'E001', name: 'Pulp Capping (Direct / Indirect)', price: 1000, category: 'Endodontics' },
  { code: 'E002', name: 'Pulpectomy', price: 1500, category: 'Endodontics' },
  { code: 'E002A', name: 'Pulpotomy', price: 1500, category: 'Endodontics' },
  { code: 'E003', name: 'Root Canal Treatment (RCT)- 1 Canal', price: 1870, category: 'Endodontics' },
  { code: 'E004', name: 'Root Canal Treatment (RCT)- 2 Canals', price: 2200, category: 'Endodontics' },
  { code: 'E005', name: 'Root Canal Treatment (RCT)- 3 Canals', price: 3000, category: 'Endodontics' },
  { code: 'E006', name: 'Root Canal Treatment (RCT)- 4 Canals', price: 3500, category: 'Endodontics' },
  { code: 'E013', name: 'Root Canal Re-Treatment (RCT) - Single Canal', price: 2430, category: 'Endodontics' },
  { code: 'E014', name: 'Root Canal Re-Treatment (RCT) - Two Canals', price: 2860, category: 'Endodontics' },
  { code: 'E015', name: 'Root Canal Re-Treatment (RCT) - Three Canals', price: 3900, category: 'Endodontics' },
  { code: 'E016', name: 'Root Canal Re-Treatment (RCT) - Four Canals', price: 4500, category: 'Endodontics' },
  { code: 'E019', name: 'Pulp Vitality Test', price: 110, category: 'Endodontics' },

  { code: 'P012', name: 'Ultrasonic Scaling', price: 700, category: 'Periodontics' },
  { code: 'P015', name: 'Air Polishing- Stains dependent', price: 1000, category: 'Periodontics' },
  { code: 'P026', name: 'Soft Tissue Graft - Free Gingival', price: 3000, category: 'Periodontics' },
  { code: 'P030', name: 'Guided Bone Regeneration (GBR) – Bone Substitute', price: 8000, category: 'Periodontics' },
  { code: 'P032', name: 'Full Mouth Periodontal Therapy (With Local Anaesthesia)', price: 1800, category: 'Periodontics' },
  { code: 'P033', name: 'Bone Graft - Substitute', price: 8000, category: 'Periodontics' },
  { code: 'P035', name: 'Crown Lengthening Surgery (Per Tooth)', price: 800, category: 'Periodontics' },
  { code: 'P037', name: 'Gummy Smile Correction (Crown Lengthening)', price: 5000, category: 'Periodontics' },
  { code: 'P040', name: 'Internal Sinus Lift', price: 9000, category: 'Periodontics' },

  { code: 'RM001', name: 'Metal Denture (Cobalt Chrome) Per Jaw/Arch', price: 2000, category: 'R-Prosthesis' },
  { code: 'RM001a', name: 'Metal Denture- Extra/Additional Teeth (More Than 1)', price: 100, category: 'R-Prosthesis' },
  { code: 'RP007', name: 'Acrylic Complete Denture Maxillary', price: 3000, category: 'R-Prosthesis' },
  { code: 'RP008', name: 'Acrylic - Complete Denture Mandibular', price: 3000, category: 'R-Prosthesis' },
  { code: 'RP011', name: 'Acrylic Partial Denture -1 Teeth (Maxillary)', price: 1000, category: 'R-Prosthesis' },
  { code: 'RP011a', name: 'Acrylic Partial Denture -1 Teeth (Mandible)', price: 1000, category: 'R-Prosthesis' },
  { code: 'RP011b', name: 'Acrylic Partial Denture -Extra Teeth (More than 1 Tooth)', price: 100, category: 'R-Prosthesis' },
  { code: 'RP011c', name: 'Acrylic Denture Repair', price: 500, category: 'R-Prosthesis' },
  { code: 'RP015', name: 'Vaplast Denture (Full Arch Upper & Lower)', price: 5800, category: 'R-Prosthesis' },
  { code: 'RP015a', name: 'Vaplast Denture (Full Arch Upper / Lower)', price: 3000, category: 'R-Prosthesis' },
  { code: 'RP018', name: 'Vaplast Denture (1 Tooth) per Jaw/Arch', price: 2000, category: 'R-Prosthesis' },
  { code: 'RP018a', name: 'Vaplast Denture-Extra/Additional Teeth (More Than 1)', price: 200, category: 'R-Prosthesis' },
  { code: 'RP018c', name: 'Vaplast Denture Repair', price: 800, category: 'R-Prosthesis' },
  { code: 'RP018C', name: 'Maryland', price: 5000, category: 'R-Prosthesis' },
  { code: 'RP021', name: 'Denture Relining – Upper (Less than 3 Years)', price: 500, category: 'R-Prosthesis' },
  { code: 'RP021a', name: 'Denture Relining – Lower (Less than 3 Years)', price: 500, category: 'R-Prosthesis' },

  { code: 'S001', name: 'Dental Abscess- Incision & Drainage', price: 500, category: 'Surgery' },
  { code: 'S0015', name: 'Frenectomy', price: 1000, category: 'Surgery' },
  { code: 'S0023', name: 'Pediatric Extraction (Deciduous Teeth)', price: 750, category: 'Surgery' },
  { code: 'S0025', name: 'Sterilization - Extracted Tooth (Adult)', price: 200, category: 'Surgery' },
  { code: 'S0027', name: 'Sterilization - Extracted Tooth (Pedo)', price: 100, category: 'Surgery' },
  { code: 'S003', name: 'Simple Extraction (Premolars)', price: 1500, category: 'Surgery' },
  { code: 'S004', name: 'Simple Extraction (Molars)', price: 2000, category: 'Surgery' },
  { code: 'S005', name: 'Simple Extraction - Anterior', price: 1000, category: 'Surgery' },
  { code: 'S007', name: 'Surgical Extraction – Impacted Tooth (Upper & Lower)', price: 3800, category: 'Surgery' },
  { code: 'S009', name: 'Surgical Extraction – Impacted Tooth (Lower Only)', price: 2500, category: 'Surgery' },
  { code: 'S012', name: 'Extraction- Wisdom Tooth', price: 2500, category: 'Surgery' },
  { code: 'S012_1', name: 'Simple Extraction-Retained Roots (Molars)', price: 2000, category: 'Surgery' },
  { code: 's013', name: 'Simple Extraction-Retained Roots Erupted (Premolars)', price: 1300, category: 'Surgery' },
  { code: 'S014', name: 'Onlay Bone Graft (Bone Substitute + Membrane)', price: 8000, category: 'Surgery' },
  { code: 'S015', name: 'Surgical Extraction – Erupted Molar (Difficult)', price: 2500, category: 'Surgery' },
  { code: 's017', name: 'Operculectomy (Gum Tissue Removal)', price: 1500, category: 'Surgery' },
  { code: 'S020', name: 'Apicectomy - retrofilling IRM', price: 3000, category: 'Surgery' },
  { code: 'S021', name: 'Apicectomy - retrofilling MTA', price: 3500, category: 'Surgery' },

  { code: 'PR001', name: 'Scaling & Polishing (Normal/ Routine)', price: 600, category: 'Prophylaxis' },
  { code: 'PR002', name: 'Scaling & Polishing (Moderate Stains)', price: 900, category: 'Prophylaxis' },
  { code: 'PR003', name: 'Scaling & Polishing (Deep/Heavy Stains & Plaque)', price: 1500, category: 'Prophylaxis' },
  { code: 'PR004', name: 'Scaling & Root Planing (SRP) - Deep/Periodontal Gum Treatment', price: 1500, category: 'Prophylaxis' },
  { code: 'PR005', name: 'Fluoride Application', price: 700, category: 'Prophylaxis' },
  { code: 'PR006', name: 'Space Maintainer Appliance (Single Unit)', price: 2000, category: 'Prophylaxis' },

  { code: 'FP001', name: 'Temporary Restoration (Acrylic Resin)', price: 1500, category: 'F-Prosthesis' },
  { code: 'FP002', name: 'Composite Veneers/Build up', price: 900, category: 'F-Prosthesis' },
  { code: 'FP0037', name: 'Gold-Plated Alloy Crown (9-karat) - Anterior', price: 12500, category: 'F-Prosthesis' },
  { code: 'FP0038', name: 'Gold-Plated Alloy Crown (11-karat) - Anterior', price: 15000, category: 'F-Prosthesis' },
  { code: 'FP0039', name: 'Gold-Plated Alloy Crown (14-karat) - Anterior', price: 16000, category: 'F-Prosthesis' },
  { code: 'FP0039A', name: 'Gold-Plated Alloy Crown (18-karat) - Anterior', price: 17500, category: 'F-Prosthesis' },
  { code: 'FP0040', name: 'Gold-Plated Alloy Crown (20-karat) - Anterior', price: 19000, category: 'F-Prosthesis' },
  { code: 'FP0041', name: 'Gold-Plated Alloy Crown (24-karat) - Anterior', price: 20000, category: 'F-Prosthesis' },
  { code: 'FP0042', name: 'Gold-Plated Alloy Crown (28-karat) - Anterior', price: 22500, category: 'F-Prosthesis' },
  { code: 'FP0043', name: 'Gold-Plated Alloy Crown (9-karat) - Posterior', price: 25000, category: 'F-Prosthesis' },
  { code: 'FP0044', name: 'Gold-Plated Alloy Crown (11-karat) - Posterior', price: 30000, category: 'F-Prosthesis' },
  { code: 'FP0045', name: 'Gold-Plated Alloy Crown (14-karat) - Posterior', price: 32000, category: 'F-Prosthesis' },
  { code: 'FP0046_1', name: 'Gold-Plated Alloy Crown (18-karat) - Posterior', price: 35000, category: 'F-Prosthesis' },
  { code: 'FP0046_2', name: 'Gold-Plated Alloy Crown (20-karat) - Posterior', price: 38000, category: 'F-Prosthesis' },
  { code: 'FP0047', name: 'Gold-Plated Alloy Crown (24-karat) - Posterior', price: 40000, category: 'F-Prosthesis' },
  { code: 'FP0048', name: 'Gold-Plated Alloy Crown (28-karat) - Posterior', price: 45000, category: 'F-Prosthesis' },
  { code: 'FP0049', name: 'Silver-plated crown', price: 1200, category: 'F-Prosthesis' },
  { code: 'FP009', name: 'Fiber Post & Core Build-Up (Glass Fiber)', price: 900, category: 'F-Prosthesis' },
  { code: 'FP010', name: 'Fiber Post & Core Build-Up (Carbon Fiber)', price: 600, category: 'F-Prosthesis' },
  { code: 'FP011', name: 'PFM - Precious Metal', price: 3500, category: 'F-Prosthesis' },
  { code: 'FP013', name: 'Full Ceramic Crown - E-max LT', price: 5000, category: 'F-Prosthesis' },
  { code: 'FP016', name: 'Full Ceramic Crown - PFM', price: 3500, category: 'F-Prosthesis' },
  { code: 'FP017', name: 'Full Ceramic Crown - Full Zirconium Pretau', price: 5000, category: 'F-Prosthesis' },
  { code: 'FP018', name: 'Metal Crown', price: 2000, category: 'F-Prosthesis' },
  { code: 'FP019_1', name: 'Veneers Direct Composite', price: 1200, category: 'F-Prosthesis' },
  { code: 'FP019_2', name: 'Crown Cementation Repair (Re-Cementation)', price: 600, category: 'F-Prosthesis' },
  { code: 'FP019a', name: 'Crown Removal & Re-Installation /Re-Cementation', price: 1000, category: 'F-Prosthesis' },
  { code: 'FP019A', name: 'Bridge Cementation Repair (Re-Cementation)', price: 1000, category: 'F-Prosthesis' },
  { code: 'FP020', name: 'Veneers Ceramic - E-max LT', price: 5000, category: 'F-Prosthesis' },
  { code: 'FP021', name: 'Veneers Ceramic - E-max HT', price: 5000, category: 'F-Prosthesis' },
  { code: 'FP022', name: 'Veneers Ceramic - E-max', price: 5000, category: 'F-Prosthesis' },
  { code: 'FP025', name: 'Veneers Ceramic - Zirconium Multi-Layer', price: 5000, category: 'F-Prosthesis' },
  { code: 'R036', name: 'Onlay Zirconia Restoration (Multi-Layer)', price: 5000, category: 'F-Prosthesis' },

  { code: 'EN001', name: 'Paediatric/Child teeth cleaning (1-5 years)', price: 500, category: 'Pedodontics' },
  { code: 'EN002', name: 'Paediatric/Child Teeth Cleaning (Above 5 yrs)', price: 700, category: 'Pedodontics' },
  { code: 'EN003', name: 'Fluoride Application', price: 700, category: 'Pedodontics' },
  { code: 'PR004_1', name: 'Paediatric/Child Cleaning + Fluoride Application', price: 1200, category: 'Pedodontics' },
  { code: 'PR008', name: 'Pit & Fissure Sealant Application', price: 500, category: 'Pedodontics' },

  { code: 'OC001', name: 'Occlusal Night Guard (2 mm)', price: 3000, category: 'Occlusodontia' }
];
